oidc:
  issuer-uri: https://dev-533919.oktapreview.com/oauth2/default
  client-id: 0oai3cezs5RGynIYw0h7
  client-secret: SQVFKnW_xuOotww9Xgri5ZIsKoX5U1fofECyD3GO

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: ${oidc.issuer-uri}
        registration:
          login:
            okta:
              client-id: ${oidc.client-id}
              client-secret: ${oidc.client-secret}
              scope: openid email profile
      resourceserver:
        jwt:
          issuer-uri: ${oidc.issuer-uri}